print("---------------------------")
print("ITEMNOOB SHOP")
print("---------------------------")
print("Water    x1ea   10 THB")
print("Coke     x1ea   10 THB")
print("Banana   x1ea   10 THB")
print("Cookie   x1ea   10 THB")
print("Red Life x1ea   10 THB")
print("Popcorn  x1ea   10 THB")
print("Stone    x1ea   10 THB")
print("Lava     x1ea   10 THB")
print("---------------------------")
print("Total : 80 THB")
print("---------------------------")
print("WELCOME TO NEW EDITOR")
print("Welcome TO Thailand")